version: "3"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customrlmaps
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - internal-customrlmaps

  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - "3000"
    networks:
      - global-reverse-proxy
      - internal-customrlmaps
    depends_on:
      - database

networks:
  global-reverse-proxy:
    driver: bridge
  internal-customrlmaps:
    driver: bridge

volumes:
  db-data:
    driver: local