version: "3"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customrlmaps
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal-customrlmaps

  purge-service:
    container_name: purge-service
    build:
      context: ./purge-service
      dockerfile: Dockerfile
    restart: always
    networks:
      - internal-customrlmaps
    depends_on:
      - database

  customrlmaps-app:
    container_name: customrlmaps-app
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - global-reverse-proxy
      - internal-customrlmaps
    depends_on:
      - database

networks:
  global-reverse-proxy:
    driver: bridge
  internal-customrlmaps:
    driver: bridge

volumes:
  db-data:
    driver: local